var  newdata = [
                {
                    "infoId": "20170300044730", 
                    "title": "材料最前沿：可自愈新材料、可弯曲超级材料", 
                    "link": "http://www.ctex.cn/article/quanzi/jhtj/201703/20170300044730.shtml", 
                    "pubDate": "2017-03-03 09:43:52", 
                    "description": "通常，自愈性材料在柔软和潮湿的条件下能很好地发挥效用。研究人员发现，当材料变干， 自愈能力会减弱。不过，日本大阪大学科学家近日研制出一种在半干燥条件下能修复99% 创口的新材料。“结合自我修复的物理、化学特性，使材料能够在更干燥、更坚硬的状态下快速有效地自愈。新材料只需要少量的水蒸气， 修复过程中，水只是充当必要的粘合剂。”科研人员介绍。", 
                    "uri": "/quanzi/jhtj", 
                    "spaceEname": "www", 
                    "imageUrl": "../img/qdbanner.png", 
                    "readRight": "0", 
                    "rank": "0", 
                    "topFlag": "0", 
                    "titleHighLight": "0", 
                    "price": "0", 
                    "source": "技E网", 
                    "infoCode": "新闻", 
                    "industry": "原创", 
                    "publishTime": "2017-03-03 09:43:52", 
                    "endTime": "2017-03-03 00:00:00", 
                    "publishTimeStr": "2017-03-03 09:43:52", 
                    "hasRlink": "0", 
                    "keyword": "精华推荐,新材料,"
                }, 
                {
                    "infoId": "20170300044729", 
                    "title": "对抗高精度武器的变色材料、近完美柔性宽频红外吸光材料、软硬重复可变的超材料、可降解“蚕丝蛋白骨钉” ", 
                    "link": "http://www.ctex.cn/article/quanzi/jhtj/201703/20170300044729.shtml", 
                    "pubDate": "2017-03-03 09:38:41", 
                    "description": "据俄塔社2017年2月23日莫斯科报道，俄罗斯电子仪器公司（隶属于俄罗斯国家技术公司）的研究人员研制出能够通过改变颜色来躲避高精度武器攻击的变色材料，该种材料可以改变颜色，甚至可以根据需要形成诸如树叶之类的复杂图像。该种涂层是一种特殊的聚合物材料，在电脉冲的作用下可以改变颜色。利用该技术形成的涂层具有低可见性，可将被保护的目标隐藏起来。目前俄罗斯完成这种变色材料模型及其控制系统的开发。", 
                    "uri": "/quanzi/jhtj", 
                    "spaceEname": "www", 
                    "imageUrl": "../img/qdbanner.png", 
                    "readRight": "0", 
                    "rank": "0", 
                    "topFlag": "0", 
                    "titleHighLight": "0", 
                    "price": "0", 
                    "source": "技E网", 
                    "infoCode": "新闻", 
                    "industry": "原创", 
                    "publishTime": "2017-03-03 09:38:41", 
                    "endTime": "2017-03-03 00:00:00", 
                    "publishTimeStr": "2017-03-03 09:38:41", 
                    "hasRlink": "0", 
                    "keyword": "精华推荐,新材料,高精度武器,"
                }, 
                {
                    "infoId": "20170200044450", 
                    "title": "能源最前沿：长寿命液流电池、“纳米发动机”电池、柔性太阳能光伏发电、低成本钙钛矿太阳能电池、高效多晶硅光伏电池……", 
                    "link": "http://www.ctex.cn/article/quanzi/jhtj/201702/20170200044450.shtml", 
                    "pubDate": "2017-02-27 13:25:13", 
                    "description": "俄罗斯科学院的研究人员正在研制一种极其微小的内燃发电机，用于为电子设备、笔记本电脑及医学芯片提供电力。目前常见的电池，其能量密度相比于常见的燃料不到十分之一，研制一种微型发电机提供电力是一种提高能量密度的解决途径。近年来，各国科学家都在积极寻找替代铅锌及锂离子电池的技术，其中燃料电池作为一种有前景的方案被广泛研究，但其通过氧化燃料的方式产生电力的效率仍低于目前常见的内燃发动机。", 
                    "uri": "/quanzi/jhtj", 
                    "spaceEname": "www", 
                    "imageUrl": "../img/qdbanner.png", 
                    "readRight": "0", 
                    "rank": "0", 
                    "topFlag": "0", 
                    "titleHighLight": "0", 
                    "price": "0", 
                    "source": "技E网", 
                    "infoCode": "新闻", 
                    "industry": "原创", 
                    "publishTime": "2017-02-27 13:25:13", 
                    "endTime": "2017-02-27 00:00:00", 
                    "publishTimeStr": "2017-02-27 13:25:13", 
                    "hasRlink": "0", 
                    "keyword": "精华推荐,太阳能电池,"
                }, 
                 
                {
                    "infoId": "20170200043563", 
                    "title": "【精华推荐】DARPA最前沿：SideArm无人机拦截系统、光纤激光半导体模块、RadioBio计划、大流行预防平台（P3）计划", 
                    "link": "http://www.ctex.cn/article/quanzi/jhtj/201702/20170200043563.shtml", 
                    "pubDate": "2017-02-09 10:03:55", 
                    "description": "2016年12月，SideArm系统顺利通过了400磅（181千克）的Lockheed Martin Fury无人机系统测试。当时，Aurora Flight ScienCES（极光飞行科学公司）是SideArm的测试方。为了增加测试难度，Aurora Flight Sciences加快了无人机的飞行速度，但SideArm还是迅速将Lockheed Martin Fury无人机系统“捕获”。虽然DARPA最初的目标是回收900磅重的无人机，但现在，SideArm的能力已经超出了原计划：其已经能够顺利回收1100磅重的无人机了。", 
                    "uri": "/quanzi/jhtj", 
                    "spaceEname": "www", 
                    "imageUrl": "../img/qdbanner.png", 
                    "readRight": "0", 
                    "rank": "0", 
                    "topFlag": "0", 
                    "titleHighLight": "0", 
                    "price": "0", 
                    "source": "技E网", 
                    "infoCode": "新闻", 
                    "industry": "原创", 
                    "publishTime": "2017-02-09 10:03:55", 
                    "endTime": "2017-02-09 00:00:00", 
                    "publishTimeStr": "2017-02-09 10:03:55", 
                    "hasRlink": "0", 
                    "keyword": "精华推荐,无人机,光纤激光,"
                }, 
                {
                    "infoId": "20170200043383", 
                    "title": "【精华推荐】DARPA最前沿：SHARE数据共享、OFFSET无人机蜂群、原型生物控制系统、电力网防护解决方案", 
                    "link": "http://www.ctex.cn/article/quanzi/jhtj/201702/20170200043383.shtml", 
                    "pubDate": "2017-02-06 10:16:25", 
                    "description": "美国国防部高级研究计划局（Defense Advanced Research Projects Agency，DARPA）启动了这样一个项目：项目试图创建一种新的数据共享技术，以实现美军可以远程在世界各地都能够安全的发出或者接收敏感信息。DARPA作为国防部门的武装研究机构，称他们正在进行的这个项目将会采用软件和网络技术来保障安全数据共享，不管用户使用的是不安全的商业网络还是军事网络。", 
                    "uri": "/quanzi/jhtj", 
                    "spaceEname": "www", 
                    "imageUrl": "../img/qdbanner.png", 
                    "readRight": "0", 
                    "rank": "0", 
                    "topFlag": "0", 
                    "titleHighLight": "0", 
                    "price": "0", 
                    "source": "技E网", 
                    "infoCode": "新闻", 
                    "industry": "原创", 
                    "publishTime": "2017-02-06 10:16:25", 
                    "endTime": "2017-02-06 00:00:00", 
                    "publishTimeStr": "2017-02-06 10:16:25", 
                    "hasRlink": "0", 
                    "keyword": "精华推荐,数据共享,无人机,"
                }, 
                {
                    "infoId": "20170200043351", 
                    "title": "【精华推荐】材料最前沿：激发石墨烯自身固有超导特性、微生物纳米线电子材料、头发韧性启迪防弹衣材料开发", 
                    "link": "http://www.ctex.cn/article/quanzi/jhtj/201702/20170200043351.shtml", 
                    "pubDate": "2017-02-04 09:36:59", 
                    "description": "在剑桥大学开展的最新一项研究中，科学家宣布，他们已经发现一种能激发石墨烯超导性的方法——将石墨烯与镨铈铜氧化物（Pr2−xCexCuO4）或PCCO材料耦合。PCCO是一种广泛存在的超导材料，此类超导材料又被称为铜氧化物（英文为cuprate，源于拉丁文copper），因其在高温超导电性领域的应用而闻名。", 
                    "uri": "/quanzi/jhtj", 
                    "spaceEname": "www", 
                    "imageUrl": "../img/qdbanner.png", 
                    "readRight": "0", 
                    "rank": "0", 
                    "topFlag": "0", 
                    "titleHighLight": "0", 
                    "price": "0", 
                    "source": "技E网", 
                    "infoCode": "新闻", 
                    "industry": "原创", 
                    "publishTime": "2017-02-04 09:36:59", 
                    "endTime": "2017-02-04 00:00:00", 
                    "publishTimeStr": "2017-02-04 09:36:59", 
                    "hasRlink": "0", 
                    "keyword": "精华推荐,石墨烯,新材料,"
                }, 
                {
                    "infoId": "20170100043327", 
                    "title": "【精华推荐】能源最前沿：细菌电池、碳基有机电池、为电池加入分子灭火器、锂离子电池绿色设计开发、", 
                    "link": "http://www.ctex.cn/article/quanzi/jhtj/201701/20170100043327.shtml", 
                    "pubDate": "2017-01-24 09:04:45", 
                    "description": "纽约州立大学宾汉姆顿分校的研究人员在一张纸上研制出以细菌为动力的电池。这种电池可以用来为一次性电子用品供电。它减少了制造时间与成本，并可能革命性地改变生物电池的用途，使其可以作为一种电源在边远、危险或资源匮乏的地区使用。研究人员表示，纸电子（Papertronics）近来已发展为一种简单、廉价的面向一次性医用传感器的供电手段。“这种独立存在、能够自我维持的纸质医疗用品，对于资源匮乏地区的医救工作而言非常重要”。", 
                    "uri": "/quanzi/jhtj", 
                    "spaceEname": "www", 
                    "imageUrl": "../img/qdbanner.png", 
                    "readRight": "0", 
                    "rank": "0", 
                    "topFlag": "0", 
                    "titleHighLight": "0", 
                    "price": "0", 
                    "source": "技E网", 
                    "infoCode": "新闻", 
                    "industry": "原创", 
                    "publishTime": "2017-01-24 09:04:45", 
                    "endTime": "2017-01-24 00:00:00", 
                    "publishTimeStr": "2017-01-24 09:04:45", 
                    "hasRlink": "0", 
                    "keyword": "精华推荐,细菌电池,"
                }, 
                
            ];

export function newfn(){
	return newdata;
}



